#script to generate a histogram to show the distribution of the gene scores generated by the Exomiser tool for each variant of the 269 hypertrophic cardiomyopathy patients under investigation.

import argparse
import glob
import os
import pandas as pd
import sys
import matplotlib.pyplot as plt

#request command line input of the run name for analysis
parser = argparse.ArgumentParser()
parser.add_argument("run_name", help='input the name of the run you are analysing')
args = parser.parse_args()

#output files from each Exomiser run were transferred from the CSD3 server to a 'exomiser_output_files' directory on the local machine
#pull all gene analysis files for specified run 
exomiser_files = glob.glob('/home/ashley/Documents/Exomiser_Project/exomiser_transfer/exomiser_output_files/' + args.run_name + '/*.genes.tsv')

#create an empty list to append gene phenotype scores 
gene_scores = []

#iterate through files, and append gene scores to empty list 
for ex in exomiser_files:
	df = pd.read_csv(ex, sep='\t')
	for index, row in df.iterrows():
		gene_scores.append(row[2])

#plot histogram of distribution of gene scores 
plt.hist(gene_scores, range=(0, 1), color = 'orangered', edgecolor = 'black')
plt.xlabel('Gene Phenotype Score', labelpad=10)
plt.ylabel('Frequency', labelpad=10)
plt.title('Distribution of Phenotype Score for all Genes with Variants', pad=10)
plt.show()
